### ISSUE TITLE
Hulu support

### ISSUE THREAD

**Issue by jluo117** [r-anime/holo#11]
This does not pull data from Hulu

**Comment by wopian** [comment]
They don't have any exclusives. I believe most of the seasonal shows they stream are via AnimeLab. They're streaming 3 this season and only had one last season.

##### Spring
- Tokyo Ghoul:re
	- AnimeLab, Aniplus, Crunchyroll, Funimation, Hulu, Wakanim
- Persona 5 The Animation
	- AnimeLab, Crunchyroll, Hulu
- Sword Art Online Alternative: Gun Gale Online
	- AnimeLab, Aniplus, Crunchyroll, Hulu, Wakanim

##### Winter
- Grancrest Senki
	- AnimeLab, Crunchyroll, Hulu, Wakanim, Aniplus

**Comment by adethise** [comment]
Perfect, thanks.

I close this issue and redirect it to #10
