### ISSUE TITLE
All discussions table does appear correct in episode discussion body

### ISSUE THREAD

**Issue by chrislbaird** [r-anime/holo#200]
I have noticed that the the Link column looks incorrect.  I have tried on multiple browsers with the same result. Current Firefox and Edge was used. 
![image](https://github.com/r-anime/holo/assets/13765955/9d165d70-f7bb-4aa7-b5c1-73fc9d77020d)

Thank you for your hard work!

**Comment by eritbh** [comment]
This appears to be an issue with how shreddit handles tables - the markup generated by the bot is fine, but shreddit styles tables in a strange way which prevents the browser from doing its normal sizing of the table columns according to contents. I don't think there's anything to be done about this issue on the bot's end.
