### ISSUE TITLE
Yu-Gi-Oh! VRAINS Posts Missing MAL Link

### ISSUE THREAD

**Issue by tableaukun** [r-anime/holo#57]
Since Yu-Gi-Oh was added in July, the discussion posts have been missing MAL links, even though one exists in the season_config (long.yaml). Latest episode: [Episode 116](https://www.reddit.com/r/anime/comments/cwj7dq). This issue affects episodes 110-116.

**Comment by bainosz** [comment]
The bug was caused by an incompletely removed entry in the database. The duplicate entry has been cleaned and the links for MAL, AL and AniDB are now correctly recorded. Changes will be applied retroactively once the next episode is posted.
