### ISSUE TITLE
Reddit episode post missing "stream" option

### ISSUE THREAD

**Issue by mnmt** [r-anime/holo#59]
From the post https://www.reddit.com/r/anime/comments/dgtbn2/boku_no_hero_academia_season_4_episode_1/, the stream for Crunchyroll wasn't posted, despite the line https://github.com/r-anime/holo/blob/59f63f8ff5343426f79d707c94760890a2ecab52/season_configs/fall_2019.yaml#L1006 being present in the config.

**Comment by bainosz** [comment]
Fixed in eb12440
