### ISSUE TITLE
Issue with fall_2020.yaml

### ISSUE THREAD

**Issue by AnirudhRahul** [r-anime/holo#74]
Shouldn't the crunchyroll link for `Haikyuu!!: To the Top Part 2` in `fall_2020.yaml` be:

`  crunchyroll: 'https://www.crunchyroll.com/haikyu|13'`

Right now it doesn't have the `|13` at the end.

**Comment by bainosz** [comment]
Correct, the lack of offset prevented the bot from reading new episodes from CR.

Fixed in 940b588
