### ISSUE TITLE
Fix localized titles

### ISSUE THREAD

**Issue by adethise** [r-anime/holo#8]
The bot is hosted in France, which leads to some titles from Crunchyroll being returned in French.

**Comment by Geo1088** [comment]
I think the easiest way to fix this will just be to get me to start hosting the code, unless you want to do it through CR somehow. My VPS is in New York, so that will correct itself.

**Comment by edpenz** [comment]
I had a PR against the old repo that added proxy support which might be relevant to this. Hosting in a single location will otherwise always have issues with some streaming services doing regional blocking/localisation.
