### ISSUE TITLE
Stream "Crunchyroll" repeated twice, the first with erroneous wrong url

### ISSUE THREAD

**Issue by mnmt** [r-anime/holo#95]
See Reddit post [here](https://www.reddit.com/r/anime/comments/oku22h/peach_boy_riverside_episode_3_discussion/) as example of the issue. The first of the two "Crunchyroll" links just links to http://crunchyroll.com/series, which leads to a 404 page

**Comment by alexmuch** [comment]
Most likely a related issue but Tsukimichi is missing streams even though it has it in the yaml config.

[Reddit post](https://www.reddit.com/r/anime/comments/oorqq4/tsuki_ga_michibiku_isekai_douchuu_episode_3/)

[Summer 2021 yaml](https://github.com/r-anime/holo/blob/master/season_configs/summer_2021.yaml)

**Comment by bainosz** [comment]
- Erroneous database entry for Peach Boy Riverside has been removed, which will guarantee that the link only appears once
- The missing streams for Tsukimichi were fixed and should be retroactively corrected in posts when the next episode gets posted

Thanks for the heads-up.
